### ISSUE TITLE
GetComponentSlot() always return -1

### ISSUE THREAD

**Issue by Fairuz-Afdhal** [markski1/SAMP-vModData#1]
GetComponentSlot function returns -1, even if componentid is valid.

**Comment by markski1** [comment]
Good catch, thanks for your contribution

**Comment by markski1** [comment]
Please open a pull request with your commit so it can be merged into the main code

**Comment by markski1** [comment]
Thanks for this. I've added your fix to the main code and listed you as a contributor.

**Comment by Fairuz-Afdhal** [comment]
Sorry I forgot to made it a PR
